import { PublicNavbar } from "@/components/layout/PublicNavbar";
import { Scale, AlertTriangle, UserX } from "lucide-react";

export default function TermsOfService() {
    return (
        <div className="min-h-screen bg-background text-foreground selection:bg-primary/30 font-sans">
            <PublicNavbar />

            <main className="container mx-auto px-6 pt-32 pb-24 max-w-4xl">
                <div className="glass-card p-8 md:p-12 rounded-[2rem] border border-border relative overflow-hidden">
                    <div className="absolute top-0 left-0 w-full h-1 bg-vibe-gradient" />

                    <div className="flex items-center gap-4 mb-8">
                        <div className="p-3 bg-indigo-500/10 rounded-2xl">
                            <Scale className="w-8 h-8 text-indigo-400" />
                        </div>
                        <div>
                            <h1 className="text-4xl font-black uppercase tracking-tight">Terms of Service</h1>
                            <p className="text-muted-foreground font-medium tracking-widest text-sm uppercase mt-1">Effective Date: March 2026</p>
                        </div>
                    </div>

                    <div className="prose prose-invert max-w-none space-y-8 text-foreground/70">
                        <section>
                            <h2 className="text-2xl font-bold text-foreground mb-4">1. Acceptance of Terms</h2>
                            <p>
                                By accessing or using VibeChat ("the Service"), you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you do not have permission to access the Service. You must be at least 18 years old to use the Anonymous Chat features.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-foreground flex items-center gap-2 mb-4">
                                <AlertTriangle className="w-5 h-5 text-yellow-400" /> 2. Acceptable Use Policy
                            </h2>
                            <p>VibeChat is a platform for genuine human connection. You explicitly agree NOT to:</p>
                            <ul className="list-disc pl-6 space-y-2 mt-4 text-muted-foreground">
                                <li>Broadcast, stream, or display sexually explicit content, nudity, or graphic violence (NSFW) in the Anonymous Chat mode.</li>
                                <li>Harass, threaten, or intimidate other users.</li>
                                <li>Use automated scripts, bots, or modified clients to bypass matchmaking or moderation algorithms.</li>
                                <li>Record, screenshot, or distribute the image/audio of other users without their explicit, prior consent.</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-foreground flex items-center gap-2 mb-4">
                                <UserX className="w-5 h-5 text-red-400" /> 3. Enforcement & Shadowbanning
                            </h2>
                            <p>
                                We employ sophisticated manual reporting and on-device AI moderation systems to enforce these Terms.
                            </p>
                            <ul className="list-disc pl-6 space-y-2 mt-4">
                                <li><strong>No Appeal Process:</strong> If our automated systems or moderation team determine you have violated the Acceptable Use Policy, your access to the Service may be restricted, shadowbanned, or permanently terminated without prior notice.</li>
                                <li><strong>Shadowbanning:</strong> VibeChat reserves the right to quarantine users who repeatedly trigger safety flags into isolated matchmaking pools containing only other flagged users. We are under no obligation to notify you of your shadowban status.</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-foreground mb-4">4. Disclaimers and Limitations of Liability</h2>
                            <p>
                                VibeChat is provided on an "AS IS" and "AS AVAILABLE" basis. As a Peer-to-Peer (P2P) platform, we do not control the content generated by users during live interactions. VibeChat, its founders, and its affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your interactions with other users on the platform.
                            </p>
                        </section>
                    </div>
                </div>
            </main>
        </div>
    );
}
